export const eventsData = {
  1: {
    id: 1,
    title: "Tarkan - Harbiye Açıkhava Konseri",
    description:
      "Türk pop müziğinin megastarı Tarkan, yeni albümü ve en sevilen şarkılarıyla Harbiye Açıkhava'da sizlerle buluşuyor. Muhteşem sahne performansı ve unutulmaz şarkılarıyla dolu bir gece sizi bekliyor.",
    image: "/events/harbiye.jpg",
    date: "15 Temmuz 2025",
    time: "21:00",
    location: "İstanbul, Harbiye Açıkhava Tiyatrosu",
    address: "Harbiye Mah. Taşkışla Cad. No:8, Şişli/İstanbul",
    artist: {
      id: 1,
      name: "Tarkan",
      image: "/artists/tarkan.jpg",
    },
    category: "pop",
    ticketTypes: [
      {
        id: 1,
        name: "Sahne Önü VIP",
        price: 1500,
        description: "Sahne önünde ayrıcalıklı alan, özel giriş ve içecek ikramı",
        available: 50,
      },
      {
        id: 2,
        name: "VIP",
        price: 1200,
        description: "Ayrıcalıklı oturma alanı ve içecek ikramı",
        available: 100,
      },
      {
        id: 3,
        name: "Tribün A",
        price: 900,
        description: "Merkezi tribün, iyi görüş açısı",
        available: 200,
      },
      {
        id: 4,
        name: "Tribün B",
        price: 750,
        description: "Yan tribün",
        available: 300,
      },
      {
        id: 5,
        name: "Arka Alan",
        price: 500,
        description: "Ayakta alan",
        available: 500,
      },
    ],
  },
  2: {
    id: 2,
    title: "Tarkan - Ankara Konseri",
    description: "Tarkan'ın Ankara'daki muhteşem konseri. En sevilen şarkılarıyla unutulmaz bir gece yaşayacaksınız.",
    image: "/events/ankara.jpg",
    date: "20 Temmuz 2025",
    time: "20:30",
    location: "Ankara, Congresium",
    address: "Eskişehir Yolu 7. km, Tepe Prime AVM yanı, Ankara",
    artist: {
      id: 1,
      name: "Tarkan",
      image: "/artists/tarkan.jpg",
    },
    category: "pop",
    ticketTypes: [
      {
        id: 1,
        name: "VIP",
        price: 1000,
        description: "Ayrıcalıklı oturma alanı ve içecek ikramı",
        available: 80,
      },
      {
        id: 2,
        name: "Tribün A",
        price: 700,
        description: "Merkezi tribün, iyi görüş açısı",
        available: 150,
      },
      {
        id: 3,
        name: "Tribün B",
        price: 500,
        description: "Yan tribün",
        available: 200,
      },
      {
        id: 4,
        name: "Genel",
        price: 350,
        description: "Genel giriş alanı",
        available: 300,
      },
    ],
  },
  3: {
    id: 3,
    title: "Duman - Rock Festivali",
    description:
      "Türk rock müziğinin efsane grubu Duman, ODTÜ Vişnelik'te rock severlerle buluşuyor. Enerjik performans ve hit şarkılarla dolu bir gece.",
    image: "/events/rock-festival.jpg",
    date: "22 Temmuz 2025",
    time: "20:00",
    location: "Ankara, ODTÜ Vişnelik",
    address: "ODTÜ Kampüsü, Vişnelik Tesisleri, Ankara",
    artist: {
      id: 2,
      name: "Duman",
      image: "/artists/duman.jpg",
    },
    category: "rock",
    ticketTypes: [
      {
        id: 1,
        name: "Sahne Önü",
        price: 800,
        description: "Sahne önünde ayakta alan",
        available: 100,
      },
      {
        id: 2,
        name: "Genel Alan",
        price: 500,
        description: "Festival alanı genel giriş",
        available: 500,
      },
      {
        id: 3,
        name: "Öğrenci",
        price: 300,
        description: "Öğrenci indirimi (öğrenci belgesi gerekli)",
        available: 200,
      },
    ],
  },
  4: {
    id: 4,
    title: "Duman - İstanbul Konseri",
    description: "Duman'ın İstanbul'daki özel konseri. Rock müziğin en iyi örnekleriyle dolu unutulmaz bir gece.",
    image: "/events/istanbul-concert.jpg",
    date: "28 Temmuz 2025",
    time: "21:30",
    location: "İstanbul, Zorlu PSM",
    address: "Zorlu Center PSM, Levazım Mah. Koru Sok. No:2 Beşiktaş/İstanbul",
    artist: {
      id: 2,
      name: "Duman",
      image: "/artists/duman.jpg",
    },
    category: "rock",
    ticketTypes: [
      {
        id: 1,
        name: "VIP",
        price: 1200,
        description: "VIP oturma alanı ve ikramlar",
        available: 60,
      },
      {
        id: 2,
        name: "Tribün",
        price: 800,
        description: "Tribün oturma alanı",
        available: 200,
      },
      {
        id: 3,
        name: "Balkon",
        price: 600,
        description: "Balkon alanı",
        available: 150,
      },
      {
        id: 4,
        name: "Genel",
        price: 400,
        description: "Genel giriş",
        available: 300,
      },
    ],
  },
  5: {
    id: 5,
    title: "Mabel Matiz - Yaz Konseri",
    description:
      "Mabel Matiz'in büyüleyici sesiyle KüçükÇiftlik Park'ta romantik bir yaz gecesi. En sevilen şarkılarıyla unutulmaz anlar.",
    image: "/events/mabel-matiz-concert.jpg",
    date: "10 Temmuz 2025",
    time: "20:30",
    location: "İstanbul, KüçükÇiftlik Park",
    address: "Tarabya Mah. Haydar Aliyev Cad. No:64 Sarıyer/İstanbul",
    artist: {
      id: 4,
      name: "Mabel Matiz",
      image: "/artists/mabel-matiz.jpg",
    },
    category: "pop",
    ticketTypes: [
      {
        id: 1,
        name: "Sahne Önü",
        price: 700,
        description: "Sahne önü özel alan",
        available: 80,
      },
      {
        id: 2,
        name: "Oturma",
        price: 500,
        description: "Oturma alanı",
        available: 150,
      },
      {
        id: 3,
        name: "Çim Alan",
        price: 350,
        description: "Çim alanda ayakta",
        available: 300,
      },
    ],
  },
  6: {
    id: 6,
    title: "Ceza - Rap Gecesi",
    description:
      "Türk rap müziğinin efsanesi Ceza, Volkswagen Arena'da rap severlerle buluşuyor. Hip-hop kültürünün en iyi örnekleri.",
    image: "/events/ceza-rap-night.jpg",
    date: "5 Ağustos 2025",
    time: "22:00",
    location: "İstanbul, Volkswagen Arena",
    address: "Huzur Mah. Maslak Ayazağa Cad. No:4 Sarıyer/İstanbul",
    artist: {
      id: 8,
      name: "Ceza",
      image: "/artists/ceza.jpg",
    },
    category: "rap",
    ticketTypes: [
      {
        id: 1,
        name: "Golden Circle",
        price: 900,
        description: "Sahne önü özel alan",
        available: 100,
      },
      {
        id: 2,
        name: "Tribün A",
        price: 600,
        description: "Alt tribün",
        available: 200,
      },
      {
        id: 3,
        name: "Tribün B",
        price: 400,
        description: "Üst tribün",
        available: 300,
      },
      {
        id: 4,
        name: "Genel",
        price: 250,
        description: "Genel giriş alanı",
        available: 500,
      },
    ],
  },
  7: {
    id: 7,
    title: "Sagopa Kajmer - Hip Hop Konseri",
    description: "Sagopa Kajmer'in derin sözleri ve güçlü rap performansıyla Ankara'da unutulmaz bir hip-hop gecesi.",
    image: "/events/sagopa-kajmer-concert.jpg",
    date: "12 Ağustos 2025",
    time: "21:00",
    location: "Ankara, MEB Şura Salonu",
    address: "Emniyet Mah. Milas Sok. No:21 Yenimahalle/Ankara",
    artist: {
      id: 9,
      name: "Sagopa Kajmer",
      image: "/artists/sagopa-kajmer.jpg",
    },
    category: "rap",
    ticketTypes: [
      {
        id: 1,
        name: "VIP",
        price: 500,
        description: "VIP oturma alanı",
        available: 50,
      },
      {
        id: 2,
        name: "Tribün",
        price: 350,
        description: "Tribün oturma",
        available: 150,
      },
      {
        id: 3,
        name: "Genel",
        price: 200,
        description: "Genel giriş",
        available: 300,
      },
    ],
  },
}

export function getEventById(id: number) {
  return eventsData[id as keyof typeof eventsData] || null
}

export function getAllEvents() {
  return Object.values(eventsData)
}
